version: "3.8"
services:
  dev:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/usr/src/app/node_modules"
      - "./:/usr/src/app"
